"""
export_model.py — Step 4: Export assembled model.

Exports:
  - model.obj          (single OBJ, groups by storey+type)
  - model.glb          (binary glTF via trimesh)
  - elements.json      (GUID → {ifc_type, storey, bbox})

Each export function is fully independent so it can be called
individually by downstream modules (e.g., seismic analysis).
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import List

import numpy as np

from extract_geometry import ElementData, SceneGraph

logger = logging.getLogger(__name__)


# ──────────────────────────────────────────────────────────────────────────────
# OBJ export
# ──────────────────────────────────────────────────────────────────────────────

def export_obj(elements: List[ElementData], output_path: str | Path) -> Path:
    """
    Write a Wavefront OBJ file.

    Groups are named  '<storey>__<ifc_type>' for easy filtering
    in Blender / MeshLab.

    Parameters
    ----------
    elements    : flat list of ElementData (order preserved)
    output_path : destination .obj path

    Returns
    -------
    Path to the written file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    vertex_offset = 0
    lines = ["# IFC → OBJ export — generated by indoornav pipeline\n"]

    for elem in elements:
        group_name = f"{elem.storey}__{elem.ifc_type}".replace(" ", "_")
        lines.append(f"\ng {group_name}")
        lines.append(f"# GUID: {elem.guid}")

        # Vertices — convert IFC Z-up → OBJ/Blender Y-up
        # IFC: (X, Y, Z=up)  →  OBJ: (X, Z, -Y)
        for v in elem.vertices:
            lines.append(f"v {v[0]:.6f} {v[2]:.6f} {-v[1]:.6f}")

        # Faces (OBJ is 1-indexed)
        for f in elem.faces:
            i0 = f[0] + vertex_offset + 1
            i1 = f[1] + vertex_offset + 1
            i2 = f[2] + vertex_offset + 1
            lines.append(f"f {i0} {i1} {i2}")

        vertex_offset += len(elem.vertices)

    output_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("OBJ saved → %s  (%d elements)", output_path, len(elements))
    return output_path


# ──────────────────────────────────────────────────────────────────────────────
# GLB / glTF export
# ──────────────────────────────────────────────────────────────────────────────

_IFC_TYPE_COLORS: dict[str, tuple] = {
    "IfcWall":            (0.80, 0.75, 0.65),
    "IfcWallStandardCase":(0.80, 0.75, 0.65),
    "IfcSlab":            (0.55, 0.55, 0.60),
    "IfcColumn":          (0.30, 0.55, 0.80),
    "IfcBeam":            (0.25, 0.45, 0.70),
    "IfcDoor":            (0.75, 0.50, 0.25),
    "IfcWindow":          (0.50, 0.80, 0.90),
    "IfcRoof":            (0.65, 0.35, 0.30),
    "IfcStair":           (0.70, 0.60, 0.40),
    "IfcStairFlight":     (0.70, 0.60, 0.40),
    "IfcRailing":         (0.40, 0.40, 0.40),
    "IfcFurnishingElement":(0.85, 0.70, 0.55),
    "IfcCovering":        (0.90, 0.88, 0.82),
}

_DEFAULT_COLOR = (0.60, 0.60, 0.60)


def _get_color(ifc_type: str) -> tuple:
    return _IFC_TYPE_COLORS.get(ifc_type, _DEFAULT_COLOR)


def export_glb(elements: List[ElementData], output_path: str | Path) -> Path:
    """
    Export the model as a binary glTF (.glb) using trimesh.

    Each IFC type becomes a separate mesh with a distinct material color.

    Returns
    -------
    Path to the written .glb file.
    """
    try:
        import trimesh  # noqa: PLC0415
    except ImportError:
        raise ImportError("trimesh is required for GLB export: pip install trimesh")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    scene = trimesh.Scene()

    # Rotation matrix: IFC Z-up → glTF/Three.js Y-up
    # Rotate -90° around X: (x, y, z) -> (x, z, -y)
    zup_to_yup = np.array([
        [1,  0,  0,  0],
        [0,  0,  1,  0],
        [0, -1,  0,  0],
        [0,  0,  0,  1],
    ], dtype=np.float64)

    for elem in elements:
        if elem.vertices.shape[0] == 0 or elem.faces.shape[0] == 0:
            continue
        try:
            # Apply Z-up → Y-up transform on vertices
            verts_yup = np.column_stack([
                elem.vertices[:, 0],
                elem.vertices[:, 2],
                -elem.vertices[:, 1],
            ])
            mesh = trimesh.Trimesh(
                vertices=verts_yup,
                faces=elem.faces,
                process=False,
            )
            r, g, b = _get_color(elem.ifc_type)
            mesh.visual = trimesh.visual.ColorVisuals(
                mesh=mesh,
                vertex_colors=np.tile(
                    [int(r * 255), int(g * 255), int(b * 255), 255],
                    (len(elem.vertices), 1),
                ),
            )
            # Name uniquely so individual elements can be addressed later
            scene.add_geometry(
                mesh,
                node_name=f"{elem.guid}",
                geom_name=f"{elem.ifc_type}__{elem.guid}",
            )
        except Exception as exc:
            logger.debug("Skipping element %s in GLB export: %s", elem.guid, exc)

    glb_bytes = scene.export(file_type="glb")
    output_path.write_bytes(glb_bytes)
    logger.info("GLB saved → %s  (%d meshes)", output_path, len(scene.geometry))
    return output_path


# ──────────────────────────────────────────────────────────────────────────────
# elements.json export
# ──────────────────────────────────────────────────────────────────────────────

def export_elements_json(elements: List[ElementData], output_path: str | Path) -> Path:
    """
    Write a lightweight JSON index mapping GUID → metadata + bounding box.

    This is the primary linkage layer for downstream structural / seismic
    analysis — it intentionally contains NO mesh data (keep it small).

    Schema
    ------
    {
      "<GUID>": {
        "ifc_type": "IfcWall",
        "storey":   "Level 1",
        "bbox": {
          "min": [x, y, z],
          "max": [x, y, z],
          "size": [dx, dy, dz]
        }
      },
      ...
    }
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    index: dict = {}
    for elem in elements:
        size = (elem.bbox_max - elem.bbox_min).tolist()
        index[elem.guid] = {
            "ifc_type": elem.ifc_type,
            "storey":   elem.storey,
            "bbox": {
                "min":  elem.bbox_min.tolist(),
                "max":  elem.bbox_max.tolist(),
                "size": size,
            },
        }

    output_path.write_text(
        json.dumps(index, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    logger.info("elements.json saved → %s  (%d entries)", output_path, len(index))
    return output_path
